export const FETCH_RECIPES = "@FETCH_RECIPES";
export const FETCH_RECIPES_SUCCESS = "@FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "@FETCH_RECIPES_FAIL";

// MealPlan
export const ADD_RECIPE_MEAL_PLAN = "@ADD_RECIPE_MEAL_PLAN";
export const REMOVE_RECIPE_MEAL_PLAN = "@REMOVE_RECIPE_MEAL_PLAN";
export const CREATE_SHOPPING_LIST = "@CREATE_SHOPPING_LIST";
